- name: Update and upgrade apt packages
  hosts: <hosts>
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade apt packages
      apt:
        upgrade: yes
        autoremove: yes
